version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - app-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: SalesWebMVC    
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge

volumes:
    app-mysql-data:
    